### ISSUE TITLE
Unable to run python project

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-python#156]
### Excepted Result:
should be able to run python project successfully.

### Actual Result:
unable to run specs. Getting below error:
```
Traceback (most recent call last):
File "check_and_install_getgauge.py", line 49, in <module>
assert_versions()
File "check_and_install_getgauge.py", line 30, in assert_versions
python_plugin_version = get_version()
File "check_and_install_getgauge.py", line 9, in get_version
data = json.loads(str(out.decode()))
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
return _default_decoder.decode(s)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
File "start.py", line 9, in <module>
from getgauge import connection, logger, lsp_server, processor
ImportError: cannot import name logger
Error ----------------------------------

[Gauge]
Failed to start gauge API: Runner with pid 35656 quit unexpectedly(exit status 1).

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 1.0.6.nightly-2019-08-01, 2bc49db
	csharp (0.10.6), dotnet (0.1.2), html-report (4.0.8), java (0.7.3), js (2.3.6), python (0.3.6), ruby (0.5.3), screenshot (0.0.1), xml-report (0.2.1)
```

### Steps to reproduce
1. create a python project `gauge init python`
2. run spces either from terminal or from vs-code `gauge run`

### Information that will help us debug
tested version:
```
Gauge version: 1.0.6.nightly-2019-08-01
Commit Hash: 2bc49db

Plugins
-------
python (0.3.6.nightly-2019-07-25)
```

**Comment by BugDiver** [comment]
The actual issue here is in `check_and_install.py`

```
```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version:
```
Gauge version: 1.0.6.nightly-2019-08-26
Commit Hash: 756d578
python (0.3.6.nightly-2019-08-28)
```
