### ISSUE TITLE
Latest version of 'protobuf' causes errors on start

### ISSUE THREAD

**Issue by ivailop** [getgauge/gauge-python#256]
**Describe the bug**
The latest version of `protobuf` has breaking changes which cause errors on start - see https://github.com/protocolbuffers/protobuf/issues/10051#issuecomment-1138671075

**To Reproduce**
Install `gauge` and run any spec, e.g.
```
gauge run specs
```

An error would occur preventing any test to run.

**Logs**

```
Compatible version of plugin python not found. Installing plugin python...
.
Successfully installed plugin 'python' version 0.3.17
Compatible version of plugin html-report not found. Installing plugin html-report...
.......................
Successfully installed plugin 'html-report' version 4.1.4
Compatible version of plugin xml-report not found. Installing plugin xml-report...
.......................
Successfully installed plugin 'xml-report' version 0.2.3
Installing required plugins.
........................
Successfully installed plugin 'screenshot' version 0.1.0
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the '/home/circleci/.pyenv/versions/3.9.13/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
File "/home/circleci/.gauge/plugins/python/0.3.17/start.py", line 11, in <module>
from getgauge import handlers, logger, processor
File "/home/circleci/.local/lib/python3.9/site-packages/getgauge/handlers.py", line 4, in <module>
from getgauge import logger, processor
File "/home/circleci/.local/lib/python3.9/site-packages/getgauge/processor.py", line 7, in <module>
from getgauge.executor import (create_execution_status_response,
File "/home/circleci/.local/lib/python3.9/site-packages/getgauge/executor.py", line 7, in <module>
from getgauge.messages.messages_pb2 import ExecutionStatusResponse, Message
File "/home/circleci/.local/lib/python3.9/site-packages/getgauge/messages/messages_pb2.py", line 6, in <module>
import getgauge.messages.spec_pb2 as spec__pb2
File "/home/circleci/.local/lib/python3.9/site-packages/getgauge/messages/spec_pb2.py", line 34, in <module>
_descriptor.EnumValueDescriptor(
File "/home/circleci/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
_message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Error occurred while waiting for runner process to finish.
Error : exit status 1
Error ----------------------------------

[Gauge]
Failed to start gauge API: Error occurred while waiting for runner process to finish.
Error : exit status 1

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
	linux, 1.4.3, f98dd40
	html-report (4.1.4), python (0.3.17), screenshot (0.1.0), xml-report (0.2.3)

Exited with code exit status 1
CircleCI received exit code 1
```

**Expected behavior**
Run without errors.

**Screenshots**

**Versions:**
 - OS: Ubuntu 20.04.4 LTS x86_64
 - Python version: 3.9

```
gauge -v
Gauge version: 1.4.3
Commit Hash: f98dd40
```

**Additional context**
`protobuf` 4.21.0 has non-backwards compatible (breaking changes) - see https://github.com/protocolbuffers/protobuf/issues/10051#issuecomment-1138671075

**Comment by chadlwilson** [comment]
Protobuf on both gauge and plugin has since been upgraded and so dont think this is an issue any longer? Please comment if this is still an issue in later pythons/gauge-pythons and we can re-open.
