### ISSUE TITLE
Gauge cant install the plugin '  ' [PyCharm Community][Gauge 1.6.3]

### ISSUE THREAD

**Issue by ZurdenRo** [getgauge/gauge-python#330]
**Describe the bug**
Gauge cant run the test because: Cant install this plugin '  '

**To Reproduce**
1. gauge run .\specs\
2. Failed to run test case.
```
$ gauge run .\specs\
```

**Logs**
```
Error ----------------------------------
[Gauge]
Failed to start gauge API: Plugin '' not installed on following locations : 

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
        windows, 1.6.3, 44ebad3
        html-report (4.3.0), python (0.4.2), screenshot (0.1.0) [C:\Users\u902159\AppData\Roaming\gauge\plugins]
```

**Expected behavior**
I expect Gauge run my test case, and didnt does it.

**Versions:**

```
Gauge version: 1.6.3
Commit Hash: 44ebad3

Plugins
-------
html-report (4.3.0)
python (0.4.2)
screenshot (0.1.0)

```
 - OS [Window 10]
 - Python 3.11.5
 - PyCharm Community 2023.2.1

**Additional context**
I think, gauge try to install a plugin empty: '  ' <- I dont know, why does gauge try to does it ?
I installed gauge using Zip file

**UPDATED**

I solved, creating a manifest.json file, but i found others problems

**Comment by ZurdenRo** [comment]
I
> I don’t know, it’s possible the plugin install doesn’t work properly on Python 3.11 on Windows for some reason, but it’s very hard to understand what you executed and what happened, and which logs had what.

**what you executed?**
I try to execute a simple test case like 'Hello world!' on SO: Window 10

**Whig log had what ?**
There is the log after executed the command: `gauge run .\specs\`
> Traceback (most recent call last):
> 
> File "C:\Users\u902159\AppData\Roaming\gauge\plugins\python\0.4.2\check_and_install_getgauge.py", line 32, in assert_versions
> getgauge_version = pkg_resources.get_distribution('getgauge').version
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\u902159\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 478, in get_distribution
> dist = get_provider(dist)
> ^^^^^^^^^^^^^^^^^^
> File "C:\Users\u902159\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 354, in get_provider
> return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
> ^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\u902159\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 909, in require
> needed = self.resolve(parse_requirements(requirements))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\u902159\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
> raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'getgauge' distribution was not found and is required by the application

**I don’t understand what you mean by “I install manually the plugin python”**

I was wrong, i never installed de plugin python. I installed gauge using **ZIP** file. Then i tried to execute a test case and the log is above. Then, I verified gauge automatically install the python plugin before to execute test case. [gauge plugin](https://docs.gauge.org/plugin.html?os=windows&language=python&ide=vscode) but the problem was still existing. 

**why your plugin install log has the text “dont recognize like command intern or external” in it after the Python command.**
I dont know, after to run the command to execute the test case, i saw the log, and then i found it the problem.
I thing when i installed gauge via ZIP file, this installation dont have the packages getgauge, that is whay the problem exist.

So I installed manual via pip the next command:  `pip install getgauge` [get-gauge](https://pypi.org/project/getgauge/). Then the problem was fixed. (sorry foy me english)
