### ISSUE TITLE
Executing out of the box example gauge-python scripts seems to display errors on the console

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/gauge-python#334]
### Description
Executing built in Gauge-Python script example displays the following on the console

### Steps to reproduce
1. run the gauge sample scripts in the gauge framework with the python plugin as follows
2. gauge run specs --verbose from the command line on windows 11 machine
3. We see the following display on the console:
gauge run specs --verbose
'My Windows machine\Python311\python.exe -m pip install getgauge==0.4.1 --user"' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
File "<My Windows machine>\AppData\Roaming\gauge\plugins\python\0.4.1\check_and_install_getgauge.py", line 40, in <module>
assert_versions()
File "<My Windows machine>\AppData\Roaming\gauge\plugins\python\0.4.1\check_and_install_getgauge.py", line 34, in assert_versions
install_getgauge("getgauge=="+expected_gauge_version)
File "<My Windows machine>\AppData\Roaming\gauge\plugins\python\0.4.1\check_and_install_getgauge.py", line 20, in install_getgauge
check_output([" ".join(install_cmd)], shell=True)
File "<My windows machine>\Program Files\Python311\Lib\subprocess.py", line 466, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\subprocess.py", line 571, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['<My Windows Machine>\\Python311\\python.exe -m pip install getgauge==0.4.1 --user']' returned non-zero exit status 1.
Python: 3.11.5
# Specification Heading
  ## Vowel counts in single word
      * Vowels in English language are "aeiou".  ...[PASS]
      * The word "gauge" has "3" vowels.         ...[PASS]
  ## Vowel counts in multiple word
      * Vowels in English language are "aeiou".  ...[PASS]
      * Almost all words have vowels

         |Word  |Vowel Count|
         |------|-----------|
         |Gauge |3          |
         |Mingle|2          |
         |Snap  |1          |
         |GoCD  |1          |
         |Rhythm|0          |    ...[PASS]

Successfully generated html-report to => <My Windows machine>\Gauge_Python\reports\html-report\index.html

Specifications: 1 executed      1 passed        0 failed        0 skipped
Scenarios:      2 executed      2 passed        0 failed        0 skipped

Total time taken: 37ms
### Information that will help us debug

* Gauge version - gauge -v
Gauge version: 1.5.1
Commit Hash: bdc0f73
* Gauge Python plugin version - 
* Python version - python (0.4.1)
* `getgauge` package version, run `pip3 show getgauge` to get it -pip3 --version
 pip 23.2.1 from <My Windows machine>\Python311\Lib\site-packages\pip (python 3.11)
* OS information - Windows 11

Is it acceptable to have errors after running the python test scripts in gauge. I plan to try and use playwright python version tool within gauge to create some automation test scripts. As, I have been running into issues, I decided to run the plain out of box install to see if any errors are encountered.  If the above output should not have any errors, can you please advise or guide on which versions I should use to ensure no errors or issues are encountered with the install. 

Thanks,
Hari

**Comment by chadlwilson** [comment]
This is probably some issue with your python environment. The plugin install is failing, but then it seems to already be installed and running/working anyway - perhaps conflicts between environments or user vs system installs.

Take a look and if you still have issues can re-open this ticket.
