### ISSUE TITLE
Extension of VS code doesn't run test case by my local ./venv

### ISSUE THREAD

**Issue by ZurdenRo** [getgauge/gauge-python#343]
**Describe the bug**
Try to running test case by spec file.

**To Reproduce**
1. Click in `run scenario` in spec file.
2. Error:
```
File "C:\Users\u902159\AppData\Roaming\gauge\plugins\python\0.4.3\check_and_install_getgauge.py", line 5, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
File "C:\Users\u902159\AppData\Roaming\gauge\plugins\python\0.4.3\start.py", line 9, in <module>
import grpc
ModuleNotFoundError: No module named 'grpc'
Error occurred while waiting for runner process to finish.
Error : exit status 1
```

**Expected behavior**
Doesnt run the test case by spec file.

**Versions:**
 - Window 10: 22H2
- Python 3.12

Gauge version: 1.6.6
Commit Hash: 209816e

Plugins
-------
html-report (4.3.1)
python (0.4.3)
screenshot (0.2.0)

**Additional context**
I have this configuration in config VS code:

```json
{
    "workbench.iconTheme": "icons",
    "editor.fontFamily": "Consolas, 'Courier New', monospace, SauceCodePro Nerd Font Mono",
    "gauge.recommendedSettings.options": "Apply & Reload",
    "json.schemas": [],
    "workbench.colorTheme": "Ocean Space Italic",
    "python.defaultInterpreterPath": "C:\\Users\\name\\Documents\\Workspace-VScode\\py-gauge\\venv\\Scripts\\python.exe",
}

```

When I execute by command line, work fine. (`gauge run spec`) because i thinking vs code running my test case by my local ./venv, but when i click in `run scenarios` in spec file, doesn't work, The extensions Gauge in VS code work fine?

**Comment by ZurdenRo** [comment]
I uninstalled all packages of python pip global and then is broken. I want the extension gauge of VS code, run my test case by my local ./venv but didn't work

**Comment by ZurdenRo** [comment]
Sorry for open the other issues, I confused myself. I solved, add the next line in the properties file `env/default/python.properties`

```
GAUGE_PYTHON_COMMAND=d:\\Usuarios\\name\\Documents\\workspace-vscode\\python\\py-gauge\\venv\\Scripts\\python.exe
```

Now when i click the spec file, the extension gauge run scenario by my local `./venv`
