### ISSUE TITLE
Use of network connection closed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#42]
Getting the network connection closed
```
Traceback (most recent call last):
  File "start.py", line 26, in <module>
    main()
  File "start.py", line 22, in main
    processor.dispatch_messages(s)
  File "C:\Python36\lib\site-packages\getgauge\processor.py", line 215, in dispatch_messages
    processors[request.messageType](request, response, socket)
  File "C:\Python36\lib\site-packages\getgauge\processor.py", line 144, in _cache_file
    reload_steps(request.cacheFileRequest.content, request.cacheFileRequest.filePath)
  File "C:\Python36\lib\site-packages\getgauge\static_loader.py", line 26, in reload_steps
    load_steps(content, file_name)
  File "C:\Python36\lib\site-packages\getgauge\static_loader.py", line 13, in load_steps
    red = RedBaron(content)
  File "C:\Python36\lib\site-packages\redbaron\redbaron.py", line 36, in __init__
    self.node_list = base_nodes.NodeList.from_fst(baron.parse(source_code), parent=self, on_attribute="root")
  File "C:\Python36\lib\site-packages\baron\baron.py", line 49, in parse
    tokens = tokenize(source_code, False)
  File "C:\Python36\lib\site-packages\baron\baron.py", line 70, in tokenize
    return mark_indentation(inner_group(space_group(_tokenize(group(split(pouet)), print_function))))
  File "C:\Python36\lib\site-packages\baron\indentation_marker.py", line 24, in mark_indentation
    return list(mark_indentation_generator(sequence))
  File "C:\Python36\lib\site-packages\baron\indentation_marker.py", line 85, in mark_indentation_generator
    the_indentation_level_changed = get_space(current) is None or get_space(current) != indentations[-1]
  File "C:\Python36\lib\site-packages\baron\indentation_marker.py", line 38, in get_space
    if len(node) < 3 or len(node[3]) == 0:
```

**Comment by sriv** [comment]
@sguptatw when exactly does the error occur? Please provide some steps

**Comment by BugDiver** [comment]
The fix should be available in `gauge-python` nightly  >= 26-03-2018
