### ISSUE TITLE
Exception when project is opened in VSCode

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#50]
**Expected behavior**
The IDE behavior should be available for python features

**Actual behavior**
The IDE features are not available
```
15:02:43.793 --> result #0: client/registerCapability: null
Traceback (most recent call last):
  File "start.py", line 36, in <module>
    main()
  File "start.py", line 25, in main
    processor.dispatch_messages(s)
  File "/Users/sswaroop/Library/Python/2.7/lib/python/site-packages/getgauge/processor.py", line 218, in dispatch_messages
    processors[request.messageType](request, response, socket)
KeyError: 31
15:02:43.925 notif #0: initialized: Connection closed [127.0.0.1:49653] cause: EOF
```
**Steps to replicate**
* Open the gauge-python project in VSCode
> The above exception occurs

**Version**
```
auge version: 0.9.8.nightly-2018-04-05
Commit Hash: 51a094a

Plugins
-------
html-report (4.0.4.nightly-2018-03-30)
java (0.6.7.nightly-2018-04-05)
js (2.2.0.nightly-2018-03-29)
python (0.2.6.nightly-2018-03-28)
```
**pip show getgauge**
```
Name: getgauge
Version: 0.2.6.dev20180328
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /.../Python/2.7/lib/python/site-packages
Requires: protobuf, redBaron, ptvsd
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by nehashri** [comment]
###Dev notes:
mostly occurs because ImplementationGlobFilePattern request is not implemented in python.

**Comment by sguptatw** [comment]
Fixed with
```
Gauge version: 0.9.8.nightly-2018-04-11
Commit Hash: 4d314ef

Plugins
-------
python (0.3.0.nightly-2018-04-13)
```
