### ISSUE TITLE
Won't build or run with Python 3.7

### ISSUE THREAD

**Issue by tpbrown** [getgauge/gauge-python#92]
### Description
Homebrew's recent update of Python3 from 3.6 to 3.7 triggered this finding.. 
TLDR: It won't work with 3.7. Appears related to redbaron (which claims it's **alpha** quality btw).
```
$ python build.py --test
ERROR:root:Failed to parse foo.py.
F..ERROR:root:Failed to parse foo.py.
.ERROR:root:Failed to parse step_impl/foo.py.
EERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
EERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
ERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
ERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
.ERROR:root:Failed to parse foo.py.
ERROR:root:Failed to parse foo.py.
F.................................................................../Users/tpbrown/checkout/gauge-python/getgauge/processor.py:58: ResourceWarning: unclosed file <_io.TextIOWrapper name='/var/folders/8y/n9rvhv7j2hz0w1b382xnbggh0000gn/T/step_impl.py' mode='r+' encoding='UTF-8'>
  response.refactorResponse.error = 'Reason: {}'.format(e.__str__())
FFFFFFFF...........................ERROR:root:Failed to parse foo.py.
.ERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
EERROR:root:Failed to parse foo.py.
FERROR:root:Failed to parse foo.py.
F...
======================================================================
ERROR: test_LspServerHandler_refactor (tests.test_lsp_server.RegistryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_lsp_server.py", line 115, in test_LspServerHandler_refactor
    res = handler.Refactor(request, None, False)
  File "/Users/tpbrown/checkout/gauge-python/getgauge/lsp_server.py", line 50, in Refactor
    refactor.refactor_step(request, res, with_location)
  File "/Users/tpbrown/checkout/gauge-python/getgauge/refactor.py", line 11, in refactor_step
    if registry.has_multiple_impls(request.oldStepValue.stepValue):
  File "/Users/tpbrown/checkout/gauge-python/getgauge/registry.py", line 110, in has_multiple_impls
    return len(self.__steps_map.get(step_text)) > 1
TypeError: object of type 'NoneType' has no len()

======================================================================
ERROR: test_LspServerHandler_step_positions (tests.test_lsp_server.RegistryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_lsp_server.py", line 78, in test_LspServerHandler_step_positions
    self.assertEqual(res.stepPositions[0].stepValue, 'foo')
  File "/Users/tpbrown/.local/share/virtualenvs/gauge-python-rNqC8Z3c/lib/python3.7/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range

======================================================================
ERROR: test_loader_populates_registry_with_duplicate_steps (tests.test_static_loader.StaticLoaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_static_loader.py", line 64, in test_loader_populates_registry_with_duplicate_steps
    self.assertTrue(registry.has_multiple_impls("print hello"))
  File "/Users/tpbrown/checkout/gauge-python/getgauge/registry.py", line 110, in has_multiple_impls
    return len(self.__steps_map.get(step_text)) > 1
TypeError: object of type 'NoneType' has no len()

======================================================================
FAIL: test_LspServerHandler_cache_file (tests.test_lsp_server.RegistryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_lsp_server.py", line 132, in test_LspServerHandler_cache_file
    self.assertTrue(registry.is_implemented('Vowels in English language are {}.'))
AssertionError: False is not true

======================================================================
FAIL: test_LspServerHandler_step_name (tests.test_lsp_server.RegistryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_lsp_server.py", line 56, in test_LspServerHandler_step_name
    self.assertTrue(res.isStepPresent)
AssertionError: False is not true

======================================================================
FAIL: test_LspServerHandler_step_names (tests.test_lsp_server.RegistryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_lsp_server.py", line 45, in test_LspServerHandler_step_names
    self.assertEqual(res.steps, ['foo'])
AssertionError: [] != ['foo']

======================================================================
FAIL: test_LspServerHandler_validate_step (tests.test_lsp_server.RegistryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_lsp_server.py", line 68, in test_LspServerHandler_validate_step
    self.assertTrue(res.isValid)
AssertionError: False is not true

======================================================================
FAIL: test_Processor_cache_file_with_changed_status (tests.test_processor.ProcessorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_processor.py", line 518, in test_Processor_cache_file_with_changed_status
    self.assertEqual(registry.is_implemented('foo {}'), True)
AssertionError: False != True

======================================================================
FAIL: test_Processor_cache_file_with_closed_status (tests.test_processor.ProcessorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_processor.py", line 546, in test_Processor_cache_file_with_closed_status
    self.assertEqual(registry.is_implemented('foo {}'), True)
AssertionError: False != True

======================================================================
FAIL: test_Processor_cache_file_with_create_status (tests.test_processor.ProcessorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_processor.py", line 530, in test_Processor_cache_file_with_create_status
    self.assertEqual(registry.is_implemented('foo {}'), True)
AssertionError: False != True

======================================================================
FAIL: test_Processor_cache_file_with_opened_status (tests.test_processor.ProcessorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_processor.py", line 503, in test_Processor_cache_file_with_opened_status
    self.assertEqual(registry.is_implemented('foo {}'), True)
AssertionError: False != True

======================================================================
FAIL: test_Processor_refactor_request (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 189, in test_Processor_refactor_request
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_Processor_refactor_request_with_add_and_remove_param (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 222, in test_Processor_refactor_request_with_add_and_remove_param
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_Processor_refactor_request_with_add_param (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 56, in test_Processor_refactor_request_with_add_param
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_Processor_refactor_request_with_add_param_and_invalid_identifier (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 92, in test_Processor_refactor_request_with_add_param_and_invalid_identifier
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_Processor_refactor_request_with_add_param_and_only_invalid_identifier (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 128, in test_Processor_refactor_request_with_add_param_and_only_invalid_identifier
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_Processor_refactor_request_with_remove_param (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 156, in test_Processor_refactor_request_with_remove_param
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_Processor_refactor_request_without_save_change_with_add_param (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 266, in test_Processor_refactor_request_without_save_change_with_add_param
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_Processor_refactor_request_without_save_changes_add_param_and_invalid_identifier (tests.test_refactor.RefactorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_refactor.py", line 301, in test_Processor_refactor_request_without_save_changes_add_param_and_invalid_identifier
    response.refactorResponse.error)
AssertionError: True != False : Reason: module 're' has no attribute '_pattern_type'

======================================================================
FAIL: test_loader_populates_registry_for_with_aliases (tests.test_static_loader.StaticLoaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_static_loader.py", line 89, in test_loader_populates_registry_for_with_aliases
    self.assertTrue(registry.is_implemented("say hello"))
AssertionError: False is not true

======================================================================
FAIL: test_loader_populates_registry_from_given_file_content (tests.test_static_loader.StaticLoaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_static_loader.py", line 26, in test_loader_populates_registry_from_given_file_content
    self.assertTrue(registry.is_implemented("print hello"))
AssertionError: False is not true

======================================================================
FAIL: test_loader_populates_registry_only_with_steps_from_given_file_content (tests.test_static_loader.StaticLoaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_static_loader.py", line 46, in test_loader_populates_registry_only_with_steps_from_given_file_content
    self.assertTrue(registry.is_implemented("print hello"))
AssertionError: False is not true

======================================================================
FAIL: test_loader_reload_registry_for_given_content (tests.test_static_loader.StaticLoaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_static_loader.py", line 101, in test_loader_reload_registry_for_given_content
    self.assertTrue(registry.is_implemented("print hello"))
AssertionError: False is not true

======================================================================
FAIL: test_loader_reload_registry_for_given_content_with_empty_arg (tests.test_static_loader.StaticLoaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tpbrown/checkout/gauge-python/tests/test_static_loader.py", line 123, in test_loader_reload_registry_for_given_content_with_empty_arg
    self.assertTrue(registry.is_implemented("print hello {}"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 126 tests in 0.475s

FAILED (failures=21, errors=3)
```
### Steps to reproduce
You can verify this with gauge-python itself:
1. ```brew install python3``` or ```brew upgrade python3``` 
2. ```pip install -r requirements.txt```
3.```python build.py --test```

### Information that will help us debug

* Gauge version
Gauge version: 1.0.0

* Gauge Python plugin version
Master/HEAD

* Python version
Python 3.7.0

* `getgauge` package version, run `pip3 show getgauge` to get it
Not needed to be installed. Was just trying to build it for 3.7.

* OS information
macOS 10.12.6

**Comment by tpbrown** [comment]
BTW - redbaron comment wasn't from looking at the above. On an existing install with specs that worked with 3.6 running in 3.7 gives errors related to 're' with the stacktrace pointing at redbaron.

**Comment by BugDiver** [comment]
@tpbrown  We could replicate this at our end with the latest python. Looks like the `redbaron` package is not compatible with the latest `python`.

**Comment by BugDiver** [comment]
@tpbrown  I have created a PR https://github.com/PyCQA/redbaron/pull/165 for the same in `redbaron`

**Comment by BugDiver** [comment]
This issue is similar to #96. The PR #98  should adress this issue.
